version: "3.8"
services:
  mariadb:
    image: mariadb:10.5
    restart: always
    container_name: taskdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task
      MYSQL_USER: parcial_user
      MYSQL_PASSWORD: parcial_password
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306:3306"

  taskmanager:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/task
      SPRING_DATASOURCE_USERNAME: parcial_user
      SPRING_DATASOURCE_PASSWORD: parcial_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
