services:
    mariadb:
        image: mariadb:10.5
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: taskdb
            MARIADB_USER: taskuser
            MARIADB_PASSWORD: taskpassword
        volumes:
            - db_data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    taskmanager:
        image: xagh/agiraldog
        depends_on:
            mariadb:
                condition: service_healthy
        environment:
            SERVER_PORT: 8080
            SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/taskdb?allowPublicKeyRetrieval=true&useSSL=false
            SPRING_DATASOURCE_USERNAME: taskuser
            SPRING_DATASOURCE_PASSWORD: taskpassword
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
        ports:
            - "8088:8080"

volumes:
    db_data:
